name: TimeRanks
main: TimeRanks\Main
version: 3.0.0-ALPHA8
api: [3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10]

load: POSTWORLD
author: Zeao.
description: Add easy ranks to your server
website: https://github.com/luca28pet/TimeRanks
commands:
 timeranks:
  description: The main command
  usage: "/timeranks check [player]"
  aliases: [tr, ranks, tranks]
  permission: timeranks.command
permissions:
 timeranks.command:
  description: "Allows to use the main command"
  default: true
 timeranks.exempt:
  description: "Exempt rankup"
  default: op
